/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        canvas: "#F5F1E8",
        "canvas-dark": "#EDE6D3",
        ink: "#3E2C20",
        "ink-light": "#5C4A3C",
        gold: "#B8860B",
        "gold-light": "#D4A017",
        "gold-soft": "#E6C76A",
        terracotta: "#A0522D",
        "frame-dark": "#5C4033",
        "frame-light": "#8B6F47",
        "frame-mid": "#6F543A",
        parchment: "#F8F1DC",
        "parchment-dark": "#EFE2BE",
        archive: "#D9CEB2",
        "success-deep": "#2F5233",
        "error-deep": "#7A2E1F",
        sepia: "#704214",
        "museum-dark": "#1A120B",
        "museum-warm": "#2D1F14",
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        serif: ['"Lora"', 'Georgia', 'serif'],
      },
      boxShadow: {
        painting: "0 20px 60px -15px rgba(62, 44, 32, 0.5), 0 0 0 12px #5C4033, 0 0 0 16px #8B6F47",
        "painting-correct": "0 0 0 4px #D4A017, 0 20px 60px -15px rgba(212, 160, 23, 0.6), 0 0 0 12px #5C4033, 0 0 0 16px #8B6F47",
        "painting-wrong": "0 0 0 4px #A0522D, 0 20px 60px -15px rgba(160, 82, 45, 0.5), 0 0 0 12px #5C4033, 0 0 0 16px #8B6F47",
        "painting-cinematic": "0 30px 80px -20px rgba(0, 0, 0, 0.6), 0 0 0 14px #5C4033, 0 0 0 18px #8B6F47, inset 0 0 40px rgba(0,0,0,0.1)",
        "archive-card": "0 2px 0 rgba(62, 44, 32, 0.05), 0 10px 20px -8px rgba(62, 44, 32, 0.15)",
        "stamp": "inset 0 0 0 2px rgba(160, 82, 45, 0.4)",
        "museum-spotlight": "0 0 120px 40px rgba(212, 160, 23, 0.1), inset 0 0 60px rgba(0,0,0,0.3)",
        "gold-glow": "0 0 30px rgba(212, 160, 23, 0.4), 0 0 60px rgba(212, 160, 23, 0.2)",
        "inner-ink": "inset 0 2px 8px rgba(62, 44, 32, 0.15)",
      },
      backgroundImage: {
        "paper-texture":
          "radial-gradient(ellipse at 15% 20%, rgba(184, 134, 11, 0.08) 0%, transparent 45%), radial-gradient(ellipse at 85% 75%, rgba(160, 82, 45, 0.06) 0%, transparent 50%), repeating-linear-gradient(0deg, rgba(62, 44, 32, 0.012) 0px, rgba(62, 44, 32, 0.012) 1px, transparent 1px, transparent 3px)",
        "file-card":
          "linear-gradient(135deg, #F8F1DC 0%, #EFE2BE 100%)",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeInScale: {
          "0%": { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        curtainReveal: {
          "0%": { opacity: "0", filter: "blur(6px)", transform: "scale(0.98)" },
          "60%": { filter: "blur(0)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        fileFlip: {
          "0%": { opacity: "0", transform: "rotateX(-90deg) translateY(-10px)", transformOrigin: "top" },
          "100%": { opacity: "1", transform: "rotateX(0) translateY(0)", transformOrigin: "top" },
        },
        typewriter: {
          "0%": { opacity: "0", letterSpacing: "0.3em" },
          "100%": { opacity: "1", letterSpacing: "normal" },
        },
        stampHit: {
          "0%": { opacity: "0", transform: "scale(2) rotate(-12deg)" },
          "60%": { opacity: "1", transform: "scale(0.9) rotate(0deg)" },
          "100%": { opacity: "1", transform: "scale(1) rotate(-2deg)" },
        },
        scorePop: {
          "0%": { opacity: "0", transform: "translateY(10px) scale(0.8)" },
          "50%": { opacity: "1", transform: "translateY(-8px) scale(1.15)" },
          "100%": { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        glowPulse: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(212, 160, 23, 0.6)" },
          "50%": { boxShadow: "0 0 0 12px rgba(212, 160, 23, 0)" },
        },
        frameGlow: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(212, 160, 23, 0.4), 0 20px 60px -15px rgba(212, 160, 23, 0.3)" },
          "50%": { boxShadow: "0 0 40px 10px rgba(212, 160, 23, 0.5), 0 20px 60px -15px rgba(212, 160, 23, 0.6)" },
        },
        shake: {
          "0%, 100%": { transform: "translateX(0)" },
          "20%": { transform: "translateX(-4px)" },
          "40%": { transform: "translateX(4px)" },
          "60%": { transform: "translateX(-3px)" },
          "80%": { transform: "translateX(3px)" },
        },
        zoomIn: {
          "0%": { opacity: "0", transform: "scale(0.5)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        badgeFloat: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-3px)" },
        },
        cameraPanIn: {
          "0%": { opacity: "0", transform: "scale(1.15)", filter: "blur(4px)" },
          "100%": { opacity: "1", transform: "scale(1)", filter: "blur(0)" },
        },
        slowZoom: {
          "0%": { transform: "scale(1)" },
          "100%": { transform: "scale(1.04)" },
        },
        detailFocus: {
          "0%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.08)", filter: "saturate(1.2) contrast(1.1)" },
          "100%": { transform: "scale(1.04)", filter: "saturate(1.1) contrast(1.05)" },
        },
        dustFloat: {
          "0%": { transform: "translateY(0) translateX(0) scale(1)", opacity: "0" },
          "10%": { opacity: "0.6" },
          "50%": { transform: "translateY(-40px) translateX(20px) scale(1.1)", opacity: "0.4" },
          "90%": { opacity: "0.3" },
          "100%": { transform: "translateY(-80px) translateX(-10px) scale(0.9)", opacity: "0" },
        },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-60px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(60px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        timelineProgress: {
          "0%": { width: "0%" },
          "100%": { width: "100%" },
        },
        spotlightDrift: {
          "0%, 100%": { transform: "translate(-50%, -50%) scale(1)", opacity: "0.25" },
          "50%": { transform: "translate(-45%, -48%) scale(1.1)", opacity: "0.35" },
        },
        photoSway: {
          "0%, 100%": { transform: "rotate(-1.5deg) translateY(0)" },
          "50%": { transform: "rotate(1.5deg) translateY(-2px)" },
        },
        paperUnfurl: {
          "0%": { opacity: "0", transform: "scaleY(0.2) scaleX(0.9)", transformOrigin: "top center" },
          "60%": { transform: "scaleY(1.02) scaleX(0.98)" },
          "100%": { opacity: "1", transform: "scaleY(1) scaleX(1)", transformOrigin: "top center" },
        },
        clueConnect: {
          "0%": { strokeDashoffset: "100", opacity: "0" },
          "100%": { strokeDashoffset: "0", opacity: "1" },
        },
        filmGrain: {
          "0%, 100%": { transform: "translate(0, 0)" },
          "10%": { transform: "translate(-2%, -1%)" },
          "20%": { transform: "translate(-3%, 2%)" },
          "30%": { transform: "translate(2%, -2%)" },
          "40%": { transform: "translate(-1%, 3%)" },
          "50%": { transform: "translate(-3%, 1%)" },
          "60%": { transform: "translate(3%, 0)" },
          "70%": { transform: "translate(0, 2%)" },
          "80%": { transform: "translate(-2%, -3%)" },
          "90%": { transform: "translate(2%, 1%)" },
        },
        scanlineMove: {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(100vh)" },
        },
        vignettePulse: {
          "0%, 100%": { opacity: "0.3" },
          "50%": { opacity: "0.45" },
        },
        markerPulse: {
          "0%, 100%": { transform: "scale(1)", opacity: "1" },
          "50%": { transform: "scale(1.4)", opacity: "0.6" },
        },
        pageFlip: {
          "0%": { transform: "perspective(1200px) rotateY(-90deg)", opacity: "0", transformOrigin: "left center" },
          "100%": { transform: "perspective(1200px) rotateY(0deg)", opacity: "1", transformOrigin: "left center" },
        },
        progressFill: {
          "0%": { width: "0%" },
          "100%": { width: "var(--progress, 50%)" },
        },
        uvScan: {
          "0%": { transform: "translateY(-100%)", opacity: "0.6" },
          "50%": { opacity: "0.9" },
          "100%": { transform: "translateY(100%)", opacity: "0.6" },
        },
        textureZoom: {
          "0%": { transform: "scale(1)", filter: "blur(0)" },
          "30%": { transform: "scale(2.5)", filter: "blur(0.5px) contrast(1.2)" },
          "70%": { transform: "scale(2.5)", filter: "blur(0.5px) contrast(1.2)" },
          "100%": { transform: "scale(1)", filter: "blur(0)" },
        },
        signatureReveal: {
          "0%": { opacity: "0", transform: "scale(1.5)", filter: "blur(8px)" },
          "40%": { opacity: "1", transform: "scale(1)", filter: "blur(0) contrast(1.3)" },
          "80%": { opacity: "1", filter: "contrast(1.3)" },
          "100%": { opacity: "1", filter: "contrast(1)" },
        },
        comparisonSlide: {
          "0%": { transform: "translateX(0%)" },
          "50%": { transform: "translateX(-50%)" },
          "100%": { transform: "translateX(0%)" },
        },
        pigmentGlow: {
          "0%, 100%": { filter: "drop-shadow(0 0 0px transparent)" },
          "50%": { filter: "drop-shadow(0 0 8px rgba(138, 43, 226, 0.6))" },
        },
        forensicScan: {
          "0%": { clipPath: "inset(0 0 100% 0)" },
          "100%": { clipPath: "inset(0 0 0 0)" },
        },
        labPulse: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(138, 43, 226, 0.4)" },
          "50%": { boxShadow: "0 0 0 12px rgba(138, 43, 226, 0)" },
        },
        dataStream: {
          "0%": { backgroundPosition: "0% 0%" },
          "100%": { backgroundPosition: "0% 100%" },
        },
        stampAuth: {
          "0%": { opacity: "0", transform: "scale(2) rotate(-20deg)" },
          "60%": { opacity: "1", transform: "scale(0.95) rotate(0deg)" },
          "100%": { opacity: "1", transform: "scale(1) rotate(-3deg)" },
        },
      },
      animation: {
        fadeInUp: "fadeInUp 0.5s cubic-bezier(0.22, 1, 0.36, 1) both",
        fadeInScale: "fadeInScale 0.4s ease-out both",
        curtainReveal: "curtainReveal 0.9s cubic-bezier(0.22, 1, 0.36, 1) both",
        fileFlip: "fileFlip 0.45s cubic-bezier(0.34, 1.56, 0.64, 1) both",
        typewriter: "typewriter 0.4s ease-out both",
        stampHit: "stampHit 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) both",
        scorePop: "scorePop 0.7s cubic-bezier(0.34, 1.56, 0.64, 1) both",
        glowPulse: "glowPulse 2s ease-in-out infinite",
        frameGlow: "frameGlow 2.5s ease-in-out infinite",
        shake: "shake 0.4s ease-in-out",
        zoomIn: "zoomIn 0.3s ease-out both",
        badgeFloat: "badgeFloat 2s ease-in-out infinite",
        cameraPanIn: "cameraPanIn 1.6s cubic-bezier(0.22, 1, 0.36, 1) both",
        slowZoom: "slowZoom 12s ease-in-out infinite alternate",
        detailFocus: "detailFocus 2.2s cubic-bezier(0.22, 1, 0.36, 1) forwards",
        dustFloat: "dustFloat 8s ease-in-out infinite",
        slideInLeft: "slideInLeft 0.7s cubic-bezier(0.22, 1, 0.36, 1) both",
        slideInRight: "slideInRight 0.7s cubic-bezier(0.22, 1, 0.36, 1) both",
        timelineProgress: "timelineProgress 1.5s cubic-bezier(0.22, 1, 0.36, 1) both",
        spotlightDrift: "spotlightDrift 10s ease-in-out infinite",
        photoSway: "photoSway 6s ease-in-out infinite",
        paperUnfurl: "paperUnfurl 0.9s cubic-bezier(0.22, 1, 0.36, 1) both",
        clueConnect: "clueConnect 1.2s ease-out forwards",
        filmGrain: "filmGrain 0.5s steps(6) infinite",
        scanlineMove: "scanlineMove 8s linear infinite",
        vignettePulse: "vignettePulse 6s ease-in-out infinite",
        markerPulse: "markerPulse 1.8s ease-in-out infinite",
        pageFlip: "pageFlip 0.8s cubic-bezier(0.22, 1, 0.36, 1) both",
        progressFill: "progressFill 1s cubic-bezier(0.22, 1, 0.36, 1) both",
        uvScan: "uvScan 3s ease-in-out infinite",
        textureZoom: "textureZoom 4s ease-in-out infinite",
        signatureReveal: "signatureReveal 2.5s ease-out forwards",
        comparisonSlide: "comparisonSlide 6s ease-in-out infinite",
        pigmentGlow: "pigmentGlow 2.5s ease-in-out infinite",
        forensicScan: "forensicScan 1.8s ease-out forwards",
        labPulse: "labPulse 2.2s ease-in-out infinite",
        dataStream: "dataStream 3s linear infinite",
        stampAuth: "stampAuth 0.7s cubic-bezier(0.34, 1.56, 0.64, 1) both",
      },
    },
  },
  plugins: [],
};
